import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $=id=>document.getElementById(id);
const viewport=$('viewport'), statusEl=$('status'), inspector=$('inspector');
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xb5886e,.028);
const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.05,100);camera.position.set(7,5.2,7.2);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;viewport.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.4,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=2;controls.maxDistance=22;controls.rotateSpeed=.7;controls.zoomSpeed=.8;controls.panSpeed=.75;controls.touches.ONE=THREE.TOUCH.ROTATE;controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;
scene.add(new THREE.HemisphereLight(0xffe9d6,0x425137,2.25));const sun=new THREE.DirectionalLight(0xfff2e5,3.3);sun.position.set(-5,8,5);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(90,90),new THREE.MeshStandardMaterial({color:0x4a5830,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-2.4;ground.receiveShadow=true;scene.add(ground);
const grid=new THREE.GridHelper(36,36,0x776a5c,0x76695b);grid.position.y=-2.38;grid.material.transparent=true;grid.material.opacity=.24;scene.add(grid);

const mats={body:new THREE.MeshStandardMaterial({color:0x302722,metalness:.45,roughness:.3}),anchor:new THREE.MeshStandardMaterial({color:0x765d4e,metalness:.18,roughness:.48}),selected:new THREE.MeshStandardMaterial({color:0xcfa8e8,emissive:0x442148,emissiveIntensity:.6,metalness:.22,roughness:.28}),spring:new THREE.LineBasicMaterial({color:0x342923,transparent:true,opacity:.72}),springSel:new THREE.LineBasicMaterial({color:0xe8c0ff}),mic:new THREE.MeshStandardMaterial({color:0x87d8ed,emissive:0x174c58,emissiveIntensity:.72}),exciter:new THREE.MeshStandardMaterial({color:0xf2a56f,emissive:0x693018,emissiveIntensity:.5})};
let bodies=[],springs=[],objects=[],tool='select',selection=null,springStart=null,paused=false,audio=null,history=[];
const sim={substeps:3,dt:1/180,gravity:0};
function remember(){history.push(JSON.stringify(exportModel()));if(history.length>30)history.shift()}
function mkBody(pos,anchor=false){const i=bodies.length;const geo=anchor?new THREE.OctahedronGeometry(.21):new THREE.SphereGeometry(.21,24,18);const mesh=new THREE.Mesh(geo,anchor?mats.anchor:mats.body);mesh.position.copy(pos);mesh.castShadow=true;mesh.userData={kind:'body',index:i,anchor,mass:1.25,damping:.16,vel:new THREE.Vector3(),rest:pos.clone()};scene.add(mesh);bodies.push(mesh);objects.push(mesh);return mesh}
function mkSpring(a,b,stiffness=340,damping=2.2,rest=null){if(a===b)return null;if(springs.some(s=>(s.userData.a===a&&s.userData.b===b)||(s.userData.a===b&&s.userData.b===a)))return null;const ua=bodies[a],ub=bodies[b];if(!ua||!ub)return null;const geo=new THREE.BufferGeometry().setFromPoints([ua.position,ub.position]);const line=new THREE.Line(geo,mats.spring);line.userData={kind:'spring',index:springs.length,a,b,stiffness,damping,rest:rest??ua.position.distanceTo(ub.position)};scene.add(line);springs.push(line);objects.push(line);return line}
function mkMic(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.25,.035,10,32),mats.mic);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.028,.028,.56,10),mats.mic);stem.rotation.z=Math.PI/2;stem.position.x=.33;g.add(ring,stem);g.position.set(2.8,1.1,1.7);g.userData={kind:'mic',gain:-8,spread:.35};scene.add(g);objects.push(g);return g}
function mkExciter(){const g=new THREE.Group();const head=new THREE.Mesh(new THREE.SphereGeometry(.18,20,16),mats.exciter);const handle=new THREE.Mesh(new THREE.CylinderGeometry(.03,.03,.65,10),new THREE.MeshStandardMaterial({color:0x75482f}));handle.rotation.z=Math.PI/2;handle.position.x=.38;g.add(head,handle);g.position.set(-2.8,2,.8);g.userData={kind:'exciter',impulse:1.6,hardness:.65};scene.add(g);objects.push(g);return g}
let mic=mkMic(),exciter=mkExciter();
function seed(){const p=[[-2.4,.8,-.7],[-1.35,1.7,-.2],[-.2,1.95,.25],[1,1.55,.7],[2.1,.75,.95],[-1.9,-.1,.35],[-.75,.45,.95],[.45,.25,-.75],[1.55,-.18,-.05],[-1.25,-1.1,-.45],[0,-1,.5],[1.35,-1.15,.28]];const anchors=new Set([0,4,9,11]);p.forEach((v,i)=>mkBody(new THREE.Vector3(...v),anchors.has(i)));[[0,1],[1,2],[2,3],[3,4],[0,5],[1,5],[1,6],[2,6],[2,7],[3,7],[3,8],[4,8],[5,6],[6,7],[7,8],[5,9],[6,9],[6,10],[7,10],[7,11],[8,11],[9,10],[10,11],[1,7],[2,8],[5,10],[6,11],[0,6]].forEach(([a,b])=>mkSpring(a,b));}
seed();
function reindex(){bodies.forEach((b,i)=>b.userData.index=i);springs.forEach((s,i)=>s.userData.index=i)}
function updateSpringGeo(s){const a=bodies[s.userData.a],b=bodies[s.userData.b];if(!a||!b)return;const p=s.geometry.attributes.position.array;p[0]=a.position.x;p[1]=a.position.y;p[2]=a.position.z;p[3]=b.position.x;p[4]=b.position.y;p[5]=b.position.z;s.geometry.attributes.position.needsUpdate=true}
function stepPhysics(){if(paused)return;for(let sub=0;sub<sim.substeps;sub++){const dt=sim.dt;const forces=bodies.map(()=>new THREE.Vector3(0,sim.gravity,0));for(const s of springs){const a=bodies[s.userData.a],b=bodies[s.userData.b];if(!a||!b)continue;const delta=new THREE.Vector3().subVectors(b.position,a.position),len=Math.max(.0001,delta.length()),dir=delta.multiplyScalar(1/len),relv=new THREE.Vector3().subVectors(b.userData.vel,a.userData.vel).dot(dir);const f=s.userData.stiffness*(len-s.userData.rest)+s.userData.damping*relv;const fv=dir.multiplyScalar(f);forces[s.userData.a].add(fv);forces[s.userData.b].sub(fv)}bodies.forEach((b,i)=>{if(b.userData.anchor){b.userData.vel.set(0,0,0);b.position.copy(b.userData.rest);return}const inv=1/Math.max(.05,b.userData.mass);b.userData.vel.addScaledVector(forces[i],inv*dt);b.userData.vel.multiplyScalar(Math.exp(-b.userData.damping*dt));b.position.addScaledVector(b.userData.vel,dt)})}}
function exportModel(){return{bodies:bodies.map(b=>({p:b.position.toArray(),anchor:b.userData.anchor,mass:b.userData.mass,damping:b.userData.damping})),springs:springs.map(s=>({a:s.userData.a,b:s.userData.b,stiffness:s.userData.stiffness,damping:s.userData.damping,rest:s.userData.rest})),mic:{p:mic.position.toArray(),gain:mic.userData.gain,spread:mic.userData.spread},exciter:{p:exciter.position.toArray(),impulse:exciter.userData.impulse,hardness:exciter.userData.hardness}}}
function clearModel(){[...bodies,...springs,mic,exciter].forEach(o=>o&&scene.remove(o));bodies=[];springs=[];objects=[]}
function importModel(m){clearModel();(m.bodies||[]).forEach(b=>{const x=mkBody(new THREE.Vector3(...b.p),b.anchor);x.userData.mass=b.mass??1.25;x.userData.damping=b.damping??.16;x.userData.rest.copy(x.position)});(m.springs||[]).forEach(s=>mkSpring(s.a,s.b,s.stiffness,s.damping,s.rest));mic=mkMic();if(m.mic){mic.position.fromArray(m.mic.p);mic.userData.gain=m.mic.gain;mic.userData.spread=m.mic.spread}exciter=mkExciter();if(m.exciter){exciter.position.fromArray(m.exciter.p);exciter.userData.impulse=m.exciter.impulse;exciter.userData.hardness=m.exciter.hardness}selection=null;updateInspector();syncAudioGraph()}
function syncAudioGraph(){if(!audio)return;audio.node.port.postMessage({t:'graph',bodies:bodies.map(b=>({mass:b.userData.mass,damping:b.userData.damping,anchor:b.userData.anchor})),springs:springs.map(s=>({a:s.userData.a,b:s.userData.b,stiffness:s.userData.stiffness,damping:s.userData.damping}))});audio.node.port.postMessage({t:'mic',gain:Math.pow(10,mic.userData.gain/20),spread:mic.userData.spread})}
async function ensureAudio(){if(audio){await audio.ctx.resume();return audio}const ctx=new AudioContext({latencyHint:'interactive'});await ctx.audioWorklet.addModule('./physics-worklet.js?v=1');const node=new AudioWorkletNode(ctx,'physical-graph',{outputChannelCount:[2]});const comp=new DynamicsCompressorNode(ctx,{threshold:-12,knee:18,ratio:5,attack:.003,release:.2});node.connect(comp).connect(ctx.destination);audio={ctx,node};await ctx.resume();syncAudioGraph();$('audio').classList.add('active');statusEl.textContent='audio on';return audio}
function strikeBody(b,amount=null){if(!b||b.userData.anchor)return;const imp=amount??exciter.userData.impulse;b.userData.vel.add(new THREE.Vector3((Math.random()-.5)*.15,1,.25).normalize().multiplyScalar(imp*.45/Math.sqrt(b.userData.mass)));ensureAudio().then(()=>audio.node.port.postMessage({t:'hit',index:b.userData.index,amount:imp*(.65+.7*exciter.userData.hardness)}))}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function pointerHit(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const bh=ray.intersectObjects(bodies,false);if(bh.length)return bh[0].object;const sh=ray.intersectObjects(springs,false);if(sh.length)return sh[0].object;for(const root of [mic,exciter]){const h=ray.intersectObject(root,true);if(h.length)return root}return null}
function planePoint(e,planeY=0){const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const pl=new THREE.Plane(new THREE.Vector3(0,1,0),-planeY),v=new THREE.Vector3();return ray.ray.intersectPlane(pl,v)?v:null}
function setSelection(o){selection=o;springStart=null;$('spring-progress').classList.add('hidden');bodies.forEach(b=>b.material=b===o?mats.selected:(b.userData.anchor?mats.anchor:mats.body));springs.forEach(s=>s.material=s===o?mats.springSel:mats.spring);updateInspector()}
function updateInspector(){['body-fields','spring-fields','mic-fields','exciter-fields'].forEach(id=>$(id).classList.add('hidden'));if(!selection){inspector.classList.add('hidden');return}inspector.classList.remove('hidden');$('selection-count').textContent='1 selected';const k=selection.userData.kind;if(k==='body'){$('inspector-title').textContent=selection.userData.anchor?'ANCHOR':'BODY';$('body-fields').classList.remove('hidden');setCtl('mass',selection.userData.mass,2);setCtl('damping',selection.userData.damping,2)}else if(k==='spring'){$('inspector-title').textContent='SPRING';$('spring-fields').classList.remove('hidden');setCtl('stiffness',selection.userData.stiffness,0);setCtl('rest-length',selection.userData.rest,2);setCtl('spring-damping',selection.userData.damping,1)}else if(k==='mic'){$('inspector-title').textContent='MICROPHONE';$('mic-fields').classList.remove('hidden');setCtl('mic-gain',selection.userData.gain,0);setCtl('mic-spread',selection.userData.spread,2)}else{$('inspector-title').textContent='EXCITER';$('exciter-fields').classList.remove('hidden');setCtl('impulse',selection.userData.impulse,2);setCtl('hardness',selection.userData.hardness,2)}}
function setCtl(id,val,d){$(id).value=val;$(id+'-out').value=Number(val).toFixed(d)}
function bindRange(id,fn,d=2){$(id).addEventListener('input',e=>{if(!selection)return;const v=+e.target.value;$(id+'-out').value=v.toFixed(d);fn(v);syncAudioGraph()})}
bindRange('mass',v=>{if(selection.userData.kind==='body'){selection.userData.mass=v;audio?.node.port.postMessage({t:'body',index:selection.userData.index,mass:v})}},2);bindRange('damping',v=>{if(selection.userData.kind==='body'){selection.userData.damping=v;audio?.node.port.postMessage({t:'body',index:selection.userData.index,damping:v})}},2);bindRange('stiffness',v=>{if(selection.userData.kind==='spring'){selection.userData.stiffness=v;audio?.node.port.postMessage({t:'spring',index:selection.userData.index,stiffness:v})}},0);bindRange('rest-length',v=>{if(selection.userData.kind==='spring')selection.userData.rest=v},2);bindRange('spring-damping',v=>{if(selection.userData.kind==='spring'){selection.userData.damping=v;audio?.node.port.postMessage({t:'spring',index:selection.userData.index,damping:v})}},1);bindRange('mic-gain',v=>{mic.userData.gain=v},0);bindRange('mic-spread',v=>{mic.userData.spread=v},2);bindRange('impulse',v=>{exciter.userData.impulse=v},2);bindRange('hardness',v=>{exciter.userData.hardness=v},2);
$('close-inspector').onclick=()=>inspector.classList.add('hidden');
$('palette').addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(!b)return;tool=b.dataset.tool;document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x===b));springStart=null;$('spring-progress').classList.add('hidden');$('hint').textContent={select:'tap objects to inspect · drag body to move · drag empty space to orbit',body:'tap ground to add a body',anchor:'tap ground to add an anchor',spring:'tap one body, then another',exciter:'tap a body to strike it',mic:'tap ground to move the microphone'}[tool]});
let dragging=null,dragPlane=null,down={x:0,y:0};renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};const h=pointerHit(e);if(tool==='select'&&h?.userData.kind==='body'){setSelection(h);dragging=h;dragPlane=new THREE.Plane().setFromNormalAndCoplanarPoint(camera.getWorldDirection(new THREE.Vector3()).negate(),h.position);controls.enabled=false}else if(tool==='select'&&h)setSelection(h)});
renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const p=new THREE.Vector3();if(ray.ray.intersectPlane(dragPlane,p)){dragging.position.copy(p);dragging.userData.rest.copy(p);dragging.userData.vel.set(0,0,0)}});
renderer.domElement.addEventListener('pointerup',e=>{if(dragging){dragging=null;controls.enabled=true;syncAudioGraph();return}if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)return;const h=pointerHit(e);if(tool==='body'||tool==='anchor'){const p=planePoint(e,.1);if(p){remember();const b=mkBody(p,tool==='anchor');setSelection(b);syncAudioGraph()}}else if(tool==='spring'){if(h?.userData.kind==='body'){if(!springStart){springStart=h;$('spring-progress').classList.remove('hidden');setSelection(h);springStart=h}else if(h!==springStart){remember();const s=mkSpring(springStart.userData.index,h.userData.index);springStart=null;$('spring-progress').classList.add('hidden');if(s)setSelection(s);syncAudioGraph()}}}else if(tool==='exciter'){if(h?.userData.kind==='body'){setSelection(exciter);strikeBody(h)}}else if(tool==='mic'){const p=planePoint(e,.1);if(p){mic.position.copy(p);setSelection(mic)}}else if(tool==='select'&&h?.userData.kind==='body'&&e.detail===2){strikeBody(h)}});
$('delete').onclick=()=>{if(!selection)return;remember();const k=selection.userData.kind;if(k==='spring'){scene.remove(selection);springs.splice(selection.userData.index,1);objects=objects.filter(o=>o!==selection);reindex()}else if(k==='body'){const idx=selection.userData.index;const doomed=springs.filter(s=>s.userData.a===idx||s.userData.b===idx);doomed.forEach(s=>scene.remove(s));springs=springs.filter(s=>!doomed.includes(s));scene.remove(selection);bodies.splice(idx,1);springs.forEach(s=>{if(s.userData.a>idx)s.userData.a--;if(s.userData.b>idx)s.userData.b--});objects=objects.filter(o=>o!==selection&&!doomed.includes(o));reindex()}selection=null;updateInspector();syncAudioGraph()};
$('reset').onclick=()=>{const raw=localStorage.getItem('physical-studio-v2');if(raw)importModel(JSON.parse(raw));else{const first=history[0];if(first)importModel(JSON.parse(first))}};$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').classList.toggle('active',paused)};$('audio').onclick=()=>ensureAudio();
window.addEventListener('beforeunload',()=>localStorage.setItem('physical-studio-v2',JSON.stringify(exportModel())));
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
history.push(JSON.stringify(exportModel()));
let last=performance.now();function animate(now){requestAnimationFrame(animate);const elapsed=Math.min(.05,(now-last)/1000);last=now;const steps=Math.max(1,Math.min(4,Math.round(elapsed/(sim.dt*sim.substeps))));for(let i=0;i<steps;i++)stepPhysics();springs.forEach(updateSpringGeo);controls.update();renderer.render(scene,camera)}requestAnimationFrame(animate);
statusEl.textContent='3D physical workspace';

const qaEnabled=[...new URLSearchParams(location.search).keys()].some(k=>k.startsWith('qa'));
if(qaEnabled){
  const finite=()=>bodies.every(b=>[...b.position.toArray(),...b.userData.vel.toArray(),b.userData.mass,b.userData.damping].every(Number.isFinite))&&springs.every(s=>[s.userData.a,s.userData.b,s.userData.stiffness,s.userData.damping,s.userData.rest].every(Number.isFinite));
  window.__PS_QA__={
    snapshot:()=>({model:structuredClone(exportModel()),camera:{position:camera.position.toArray(),target:controls.target.toArray(),zoom:camera.zoom},renderer:{memory:{...renderer.info.memory},render:{...renderer.info.render}},paused,finite:finite()}),
    exportModel:()=>structuredClone(exportModel()),
    importModel:m=>{importModel(structuredClone(m));return structuredClone(exportModel())},
    step:n=>{const was=paused;paused=false;for(let i=0;i<Math.max(1,n|0);i++)stepPhysics();paused=was;springs.forEach(updateSpringGeo);return finite()},
    hit:(index=1,amount=1)=>{const b=bodies[index];if(b&&!b.userData.anchor){b.userData.vel.y+=amount;return true}return false},
    setBody:(index,patch={})=>{const b=bodies[index];if(!b)return false;if(patch.mass!=null)b.userData.mass=patch.mass;if(patch.damping!=null)b.userData.damping=patch.damping;if(Array.isArray(patch.position)){b.position.fromArray(patch.position);b.userData.rest.copy(b.position)}return true},
    reset:()=>{importModel(JSON.parse(history[0]));return finite()},
    validate:()=>({finite:finite(),invalidSprings:springs.filter(s=>!bodies[s.userData.a]||!bodies[s.userData.b]).map(s=>s.userData.index),anchors:bodies.filter(b=>b.userData.anchor).map(b=>({index:b.userData.index,p:b.position.toArray(),rest:b.userData.rest.toArray()}))})
  };
}
