(()=>{
'use strict';
const core=document.getElementById('core'),photo=document.getElementById('photo'),shade=document.getElementById('shade'),photoTop=document.getElementById('photoTop'),photoStatus=document.getElementById('photoStatus'),photoPhenotype=document.getElementById('photoPhenotype'),spinner=document.getElementById('spinner'),notice=document.getElementById('notice'),renderBtn=document.getElementById('renderPhoto'),dnaBtn=document.getElementById('showDNA');
let rendering=false,lastPrompt='',lastDigest='',puterPromise=null;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
function doc(){try{return core.contentDocument}catch(e){return null}}
function controls(){const d=doc(),out=[];if(!d)return out;d.querySelectorAll('#controlList .control').forEach(row=>{const input=row.querySelector('input[type=range][data-key]'),label=row.querySelector('label');if(input)out.push({key:input.dataset.key,label:(label?.textContent||input.dataset.key).trim(),value:Number(input.value)/100});});return out}
function values(){const o={};for(const x of controls())o[x.key]=x.value;return o}
function val(o,k,f=.5){return Number.isFinite(o[k])?clamp(o[k]):f}
function currentMeta(){const d=doc();return{phenotype:(d&&d.getElementById('flowerstat')?.textContent||'novel flowering plant').trim(),digest:(d&&d.getElementById('digest')?.textContent||'').trim()}}
function level(x,lo='low',mid='moderate',hi='strong'){return x<.32?lo:x>.68?hi:mid}
function pigment(o){const a=val(o,'anthocyanin'),c=val(o,'carotenoid'),g=val(o,'chlorophyll'),sat=val(o,'pigmentSaturation'),light=val(o,'pigmentLightness');let hue='cream to soft neutral';if(a>.62&&c>.58)hue='warm scarlet, coral, orange-red and golden undertones';else if(a>.62)hue='anthocyanin-rich crimson, magenta, violet or blue-purple';else if(c>.58)hue='carotenoid-rich yellow, gold and orange';else if(g>.62)hue='unusual but botanically plausible pale green to chartreuse petal tissue';else if(a>.42)hue='soft pink, mauve or lavender';else if(c>.42)hue='pale yellow to apricot';return `${hue}; ${level(sat,'muted','natural','rich')} saturation; ${light<.34?'deep':light>.68?'pale/luminous':'mid-value'} petal lightness`}
function buildPrompt(){
 const list=controls(),o=Object.fromEntries(list.map(x=>[x.key,x.value])),m=currentMeta();
 const petalCount=Math.max(3,Math.round(3+val(o,'petalNumber')*45)),whorls=Math.max(1,Math.round(1+val(o,'whorlNumber')*7));
 const bilateral=val(o,'bilateral'),sym=bilateral>.68?'strong bilateral symmetry with clearly different dorsal, lateral and ventral organs':bilateral<.32?'strong radial symmetry':'weak to moderate bilateral bias within an otherwise radial flower';
 const fusion=val(o,'petalFusion'),tube=val(o,'tubeDepth'),lip=val(o,'lipIdentity'),spur=val(o,'spurGrowth'),aspect=val(o,'petalAspect'),overlap=val(o,'petalOverlap');
 const cup=val(o,'cupCurvature'),reflex=val(o,'reflex'),twist=val(o,'twist'),ruffle=val(o,'ruffle'),serr=val(o,'serration'),fringe=val(o,'fringe'),thick=val(o,'thickness'),cones=val(o,'epidermalCones');
 const spots=val(o,'spots'),stripes=val(o,'stripes'),specks=val(o,'speckles'),throat=val(o,'throatBlotch'),band=val(o,'marginBand'),grad=val(o,'pigmentGradient'),veins=val(o,'venationDensity'),patternScale=val(o,'patternScale');
 const stamens=Math.max(1,Math.round(2+val(o,'stamenNumber')*34)),stamenLen=val(o,'stamenLength'),anther=val(o,'antherSize'),spread=val(o,'filamentSpread'),style=val(o,'styleLength'),stigma=val(o,'stigmaSize'),pollen=val(o,'pollenDisplay'),center=val(o,'centerOpenness');
 const cluster=val(o,'solitaryCluster'),disk=val(o,'compositeDisk'),branch=val(o,'branching'),density=val(o,'clusterDensity'),ped=val(o,'pedicelLength'),bract=val(o,'bractSize'),leaf=val(o,'leafBroadness'),lobing=val(o,'leafLobing');
 const noise=val(o,'developmentalNoise'),asym=val(o,'asymmetry'),scale=val(o,'organScale'),depth=val(o,'depth'),phyllo=val(o,'phyllotaxis'),stability=val(o,'stability'),plasticity=val(o,'plasticity');
 const identity=`A/B/C/E floral-organ identity proxies ${(val(o,'aIdentity')).toFixed(2)}/${val(o,'bIdentity').toFixed(2)}/${val(o,'cIdentity').toFixed(2)}/${val(o,'eIdentity').toFixed(2)}; petaloidy ${val(o,'petaloidy').toFixed(2)}; staminoidy ${val(o,'staminoidy').toFixed(2)}; dorsal-ventral contrast ${val(o,'dorsoventral').toFixed(2)}`;
 const architecture=[`${petalCount} primary petal/tepal initiation cue with about ${whorls} floral whorl${whorls===1?'':'s'}`,sym,fusion>.66?'substantially fused corolla':fusion<.34?'mostly separate petals':'partially fused petal bases',tube>.66?'deep tubular/campanulate throat':tube<.34?'open shallow throat':'moderate corolla tube',lip>.62?'pronounced specialized lower lip/labellum':'',spur>.62?'one or more visible nectar-spur-like extensions':'',aspect>.67?'long narrow petals':aspect<.33?'broad rounded petals':'intermediate petal proportions',overlap>.67?'heavy petal overlap':overlap<.33?'open petals with little overlap':'moderate overlap'].filter(Boolean).join('; ');
 const growth=`auxin transport ${level(val(o,'auxinTransport'))}; polarity ${level(val(o,'polarityStrength'))}; parallel/perpendicular growth ${val(o,'parallelGrowth').toFixed(2)}/${val(o,'perpGrowth').toFixed(2)}; margin/distal/basal growth ${val(o,'marginGrowth').toFixed(2)}/${val(o,'distalGrowth').toFixed(2)}/${val(o,'basalGrowth').toFixed(2)}; developmental duration ${val(o,'growthDuration').toFixed(2)}`;
 const surface=[cup>.66?'strong cupping':cup<.34?'fairly flat presentation':'gentle cupping',reflex>.66?'strongly reflexed outer petals':reflex>.38?'some reflexing':'little reflexing',twist>.65?'visible torsion/twisting':'subtle petal torsion',ruffle>.65?'strongly ruffled margins':ruffle>.36?'gently undulating margins':'mostly smooth margins',serr>.65?'fine serration':'',fringe>.65?'fringed/fimbriate edge':'',thick>.65?'substantial waxy petal tissue':thick<.33?'very thin translucent petal tissue':'normal petal thickness',cones>.62?'fine MIXTA-like conical epidermal texture':''].filter(Boolean).join('; ');
 const patterns=[spots>.55?`${level(spots)} spots`:null,stripes>.55?`${level(stripes)} longitudinal/radial striping`:null,specks>.55?`${level(specks)} fine speckling`:null,throat>.55?`${level(throat)} throat blotch`:null,band>.55?`${level(band)} contrasting margin band`:null,grad>.45?`${level(grad)} pigment gradient`:null,veins>.42?`${level(veins)} visible petal venation`:null,`pattern scale ${patternScale<.35?'fine':patternScale>.7?'coarse':'medium'}`].filter(Boolean).join('; ');
 const repro=`about ${stamens} visible stamens; ${stamenLen>.66?'long exserted':stamenLen<.34?'short recessed':'medium-length'} filaments; ${anther>.66?'large':'moderate'} anthers; ${spread>.62?'widely spreading':'compact'} filament arrangement; ${style>.62?'prominent elongated':'moderate'} style; ${stigma>.62?'large':'small-to-medium'} stigma; ${pollen>.58?'obvious realistic pollen':'subtle pollen'}; ${center>.62?'open exposed reproductive center':'partly enclosed center'}`;
 const support=`${disk>.65?'strong composite-head/disk-floret tendency; ':''}${cluster>.68?'clustered inflorescence with multiple blossoms':cluster<.34?'single dominant bloom':'small loose cluster'}; ${branch>.58?'visible branching flowering stems':'simple support stem'}; ${density>.67?'dense cluster spacing':'natural airy spacing'}; ${ped>.62?'long pedicels':'short-to-medium pedicels'}; ${bract>.58?'visible sepals/bracts':'restrained bracts'}; ${leaf>.62?'broad leaves':'narrow-to-medium leaves'}${lobing>.62?' with clear lobing/dissection':''}`;
 const dev=`${noise>.68?'high':noise<.32?'low':'moderate'} developmental noise; ${asym>.62?'noticeable but plausible':'subtle'} asymmetry; ${scale>.65?'large':'medium'} organ scale; ${depth>.65?'strong':'natural'} three-dimensional floral depth; ${phyllo>.6?'noticeable':'small'} phyllotactic offset; ${stability>.65?'high':'moderate'} canalization; ${plasticity>.65?'high':'restrained'} developmental plasticity`;
 const vector=list.map(x=>`${x.label}=${x.value.toFixed(2)}`).join('; ');
 return `Create a genuinely photorealistic macro botanical photograph of ONE living flowering plant phenotype generated from a synthetic DNA/regulatory-development model. It must look like a real camera photograph, not CGI, not a digital painting, not a 3D render, not vector art.\n\nGenome phenotype neighborhood: ${m.phenotype||'novel hybrid flowering plant'}. Treat the name only as a loose botanical neighborhood, never a rigid species template. Obey the genetic phenotype below even when it creates a plausible unfamiliar hybrid.\n\nORGAN IDENTITY: ${identity}.\nFLORAL ARCHITECTURE: ${architecture}.\nGROWTH / POLARITY: ${growth}.\nPETAL SURFACE / CURVATURE: ${surface}.\nPIGMENT BIOLOGY: ${pigment(o)}.\nPATTERN FORMATION: ${patterns}.\nREPRODUCTIVE ORGANS: ${repro}.\nINFLORESCENCE / SUPPORT: ${support}.\nDEVELOPMENTAL VARIATION: ${dev}.\n\nFULL 72-PATHWAY GENETIC CONTROL VECTOR (all values must influence the phenotype, with pleiotropic interactions rather than independent decorative effects): ${vector}.\n\nRender authentic botanical anatomy: real petal thickness and translucency, subsurface transmitted sunlight, fine veins, realistic stamens/anthers/pollen/pistil, believable sepals, stems and leaves, slight edge wear and tiny natural imperfections. Natural outdoor or greenhouse light, shallow depth of field, realistic lens bokeh, true macro-photo exposure and color response. The bloom should occupy most of the frame. No text, labels, borders, diagrams, fantasy glow, plastic surfaces, impossible floating organs, or decorative illustration effects. Photograph it as though a skilled macro photographer found this genetically unusual but biologically plausible flower growing in a garden.`;
}
function loadPuter(){if(window.puter?.ai?.txt2img)return Promise.resolve(window.puter);if(puterPromise)return puterPromise;puterPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://js.puter.com/v2/';s.async=true;s.onload=()=>window.puter?.ai?.txt2img?resolve(window.puter):reject(new Error('Puter image API did not initialize'));s.onerror=()=>reject(new Error('Could not load photographic image service'));document.head.appendChild(s)});return puterPromise}
function showPhoto(){photo.classList.add('show');shade.classList.add('show');photoTop.classList.add('show');core.style.visibility='hidden'}
function showDNA(){photo.classList.remove('show');shade.classList.remove('show');photoTop.classList.remove('show');core.style.visibility='visible'}
async function renderPhoto(){if(rendering)return;const d=doc();if(!d||!d.querySelector('#controlList input[data-key]')){photoStatus.textContent='DNA engine still loading';return}rendering=true;spinner.classList.add('show');renderBtn.disabled=true;renderBtn.textContent='GENERATING…';notice.classList.add('hidden');const meta=currentMeta(),prompt=buildPrompt();lastPrompt=prompt;lastDigest=meta.digest;photoPhenotype.textContent=(meta.phenotype||'novel phenotype')+' · '+(meta.digest||'');try{photoStatus.textContent='loading photographic model…';await loadPuter();photoStatus.textContent='DNA → phenotype → photograph…';const ratio=innerWidth>innerHeight?{w:16,h:9}:{w:9,h:16};const img=await window.puter.ai.txt2img({prompt,provider:'openai-image-generation',model:'gpt-image-2',quality:'high',ratio});await new Promise((resolve,reject)=>{if(img.complete&&img.naturalWidth)return resolve();img.onload=resolve;img.onerror=reject});photo.src=img.src;showPhoto();photoStatus.textContent='photographic render · current DNA';}catch(err){console.error(err);photoStatus.textContent='photo generation failed';notice.classList.remove('hidden');notice.innerHTML='The DNA engine is still working. Photo generation did not complete. Try <b>Generate photograph</b> again; the image service may ask you to sign in or approve model use.';}finally{spinner.classList.remove('show');renderBtn.disabled=false;renderBtn.textContent='GENERATE PHOTOGRAPH';rendering=false}}
renderBtn.addEventListener('click',renderPhoto);dnaBtn.addEventListener('click',()=>{if(photo.classList.contains('show'))showDNA();else if(photo.src)showPhoto()});
core.addEventListener('load',()=>{photoStatus.textContent='DNA engine ready · adjust sliders'});
window.__GENOME_PHOTO_TEST__={buildPrompt,controls,values,currentMeta,loadPuter,get lastPrompt(){return lastPrompt},get lastDigest(){return lastDigest}};
})();
