function estimateBounds(){var st=pathStepper(),mnx=1e9,mxx=-1e9,mny=1e9,mxy=-1e9,n=0;for(var i=0;i<4200;i++){var q=st();if(i<250)continue;var cs=topology(q);for(var j=0;j<Math.min(cs.length,2);j++){var c=compose(cs[j]),x=c[0],y=c[1];if(isFinite(x)&&isFinite(y)&&Math.abs(x)<1e4&&Math.abs(y)<1e4){mnx=Math.min(mnx,x);mxx=Math.max(mxx,x);mny=Math.min(mny,y);mxy=Math.max(mxy,y);n++}}}if(n<200||mxx-mnx<.001||mxy-mny<.001)return null;return {minX:mnx,maxX:mxx,minY:mny,maxY:mxy,w:mxx-mnx,h:mxy-mny}}
function clear(){acc.fill(0);ctx.fillStyle=inverted?'#fff':'#000';ctx.fillRect(0,0,W,H)}
function deposit(px,py,w,R,body){var ix=px|0,iy=py|0;if(ix<2||iy<2||ix>=W-2||iy>=H-2)return;var id=iy*W+ix;acc[id]+=w;var sx=clamp(R.spreadX+body*.18,0,1.8),sy=clamp(R.spreadY+body*.18,0,1.8),wx=w*.16*sx,wy=w*.16*sy;acc[id-1]+=wx;acc[id+1]+=wx;acc[id-W]+=wy;acc[id+W]+=wy;if(body>1){var d=w*.055*body;acc[id-W-1]+=d;acc[id-W+1]+=d;acc[id+W-1]+=d;acc[id+W+1]+=d}}
function flush(R,ink){var max=0,i;for(i=0;i<acc.length;i++)if(acc[i]>max)max=acc[i];var d=img.data,base=inverted?255:0,sgn=inverted?-1:1,scale=(ink/100)*255*R.exposure/(Math.pow(max||1,R.gamma));for(i=0;i<acc.length;i++){var v=Math.min(255,Math.pow(acc[i],R.gamma)*scale),c=clamp(base+sgn*v,0,255),o=i*4;d[o]=d[o+1]=d[o+2]=c;d[o+3]=255}ctx.putImageData(img,0,0)}
function render(preview){var my=++token;clear();setStatus(preview?'preview':'render');var total=preview?Math.min(22000,+$('quality').value):+$('quality').value,R=renderParams(),ink=+$('ink').value,body=+$('size').value,fill=+$('fill').value/100;if(!camera)camera=estimateBounds();if(!camera){setStatus('collapsed');return}var scale=Math.min(W*fill/camera.w,H*fill/camera.h),cx=(camera.minX+camera.maxX)/2,cy=(camera.minY+camera.maxY)/2,st=pathStepper(),marks=0,steps=0,t0=0;function frame(){if(my!==token)return;t0=performance.now();while(marks<total&&(performance.now()-t0)<5.2){var q=st();steps++;if(steps<180)continue;var copies=topology(q);for(var j=0;j<copies.length&&marks<total;j++){var c=compose(copies[j]),x=c[0],y=c[1],gate=.5+.5*Math.sin(x*R.fx+y*R.fy+R.phase+steps*R.temporal);if(Math.random()<R.skip||gate<R.mask)continue;var basePx=W/2+(x-cx)*scale,basePy=H/2-(y-cy)*scale,bright=clamp(1+R.brightness*Math.sin((x-y)*(R.fx*.73)+(x+y)*(R.fy*.41)+R.phase),.12,2.4);for(var sp=0;sp<R.split&&marks<total;sp++){var aa=sp*Math.PI*2/R.split+R.phase*.17,rad=R.splitRadius*(sp?1:.25),px=basePx+Math.cos(aa)*rad+(Math.random()-.5)*R.jitter+R.streak*Math.sin(y*R.fy+R.phase),py=basePy+Math.sin(aa)*rad+(Math.random()-.5)*R.jitter+R.streak*Math.cos(x*R.fx-R.phase);deposit(px,py,bright,R,body);marks++}}}$('marks').textContent=marks.toLocaleString()+' marks';if(marks<total){requestAnimationFrame(frame)}else{flush(R,ink);setStatus(preview?'preview':'done')}}requestAnimationFrame(frame)}
function renderSources(){var box=$('sources');box.innerHTML='';SOURCES.forEach(function(s){var b=document.createElement('button');b.textContent=s[1];if(s[0]===source)b.className='active';b.onclick=function(){source=s[0];seedGenome();camera=null;renderSources();render(false)};box.appendChild(b)})}
function renderStructs(){var box=$('structures');box.innerHTML='';STRUCTS.forEach(function(s){var b=document.createElement('button');b.textContent=s[1];if(s[0]===structure)b.className='active';b.onclick=function(){structure=s[0];source=s[2];seed=s[3];seedGenome();renderStructs();renderSources();renderGenes();$('seedText').textContent='seed '+seed;render(false)};box.appendChild(b)})}
function renderBanks(){var box=$('banks');box.innerHTML='';BANKS.forEach(function(bk,i){var b=document.createElement('button');b.textContent=bk[0]+' '+bk[3];if(i===bankIndex)b.className='active';b.onclick=function(){bankIndex=i;renderBanks();renderGenes()};box.appendChild(b)});$('bankNote').textContent=BANKS[bankIndex][4]}
function renderGenes(){var box=$('genes'),bk=BANKS[bankIndex],start=bk[2],len=bk[3];box.innerHTML='';var roles=['amplitude','frequency','phase','shape'];for(let j=0;j<len;j++){let idx=start+j,row=document.createElement('div');row.className='gene';let top=document.createElement('div');top.className='gtop';let nm=document.createElement('span');nm.textContent=bk[1]+'-'+String(j+1).padStart(2,'0');let vl=document.createElement('span');vl.textContent=genome[idx].toFixed(3);top.append(nm,vl);let rt=document.createElement('div');rt.className='route';rt.textContent=roles[j%4]+' → '+bk[4];let inp=document.createElement('input');inp.type='range';inp.min=-1000;inp.max=1000;inp.value=Math.round(genome[idx]*1000);inp.oninput=function(){genome[idx]=+this.value/1000;vl.textContent=genome[idx].toFixed(3);setStatus(bk[1]+' '+String(j+1).padStart(2,'0')+' · '+roles[j%4]);schedule(true)};inp.onchange=function(){schedule(false)};row.append(top,rt,inp);box.appendChild(row)}}
function mutate(frac){var r=rng((seed^Date.now())>>>0),n=Math.max(1,Math.round(N*frac));for(var i=0;i<n;i++){var ix=(r()*N)|0;genome[ix]=clamp(genome[ix]+(r()*2-1)*(.25+frac),-1,1)}seed=(seed+((r()*999999)|0)+1)>>>0;$('seedText').textContent='seed '+seed;renderGenes();render(false)}
function hunt(){var tries=0;function go(){if(tries++>12){setStatus('no visible seed');return}seed=(Math.random()*1e9)>>>0;seedGenome();camera=estimateBounds();if(camera){$('seedText').textContent='seed '+seed;renderGenes();render(false)}else setTimeout(go,0)}go()}
function labels(){$('qv').textContent=(+$('quality').value/1000)+'K';$('iv').textContent=$('ink').value;$('sv').textContent=$('size').value;$('fv').textContent=$('fill').value+'%'}
$('focus').onclick=function(){var on=document.body.classList.toggle('full');this.textContent=on?'Controls':'Focus'};$('newG').onclick=function(){seed=(Math.random()*1e9)>>>0;seedGenome();$('seedText').textContent='seed '+seed;renderGenes();render(false)};$('mut2').onclick=function(){mutate(.02)};$('mut8').onclick=function(){mutate(.08)};$('refit').onclick=function(){camera=estimateBounds();render(false)};$('render').onclick=function(){render(false)};$('hunt').onclick=hunt;$('invert').onclick=function(){inverted=!inverted;render(false)};$('save').onclick=function(){var a=document.createElement('a');a.download='attractor-'+seed+'.png';a.href=cv.toDataURL('image/png');a.click()};['quality','ink','size','fill'].forEach(function(id){$(id).oninput=function(){labels();schedule(true)};$(id).onchange=function(){schedule(false)}});
seedGenome();renderSources();renderStructs();renderBanks();renderGenes();labels();$('seedText').textContent='seed '+seed;render(false);
