#!/usr/bin/env python3
from pathlib import Path

p = Path('scripts/room_engine_v5_core.py')
s = p.read_text()

anchor = '''def _memory_worthy(message):\n    cognition = message.get("cognition") if isinstance(message, dict) else {}\n    cognition = cognition if isinstance(cognition, dict) else {}\n    return _memory_worthy_text(message.get("text", ""), cognition.get("move_type"))\n\n\n'''
insert = anchor + '''def _memory_relevant_to_listener(message, listener):\n    """Only direct or explicitly mentioned speech becomes another mind's durable memory."""\n    if not isinstance(message, dict) or listener not in ORDER:\n        return False\n    speaker = str(message.get("speaker") or "").strip().lower()\n    if listener == speaker:\n        return False\n    cognition = message.get("cognition") if isinstance(message.get("cognition"), dict) else {}\n    target_entity = str(cognition.get("target") or "").strip().lower()\n    if target_entity == listener:\n        return True\n    listener_name = str(N.get(listener, listener)).strip().lower()\n    words = set(re.findall(r"[a-z][a-z'-]*", str(message.get("text") or "").lower()))\n    return listener in words or listener_name in words\n\n\ndef _dedupe_memories(items, limit=220):\n    kept = []\n    for item in reversed(list(items or [])):\n        if not isinstance(item, dict):\n            continue\n        text = str(item.get("text") or "").strip()\n        speaker = str(item.get("speaker") or "").strip().lower()\n        if any(\n            speaker == str(prior.get("speaker") or "").strip().lower()\n            and _sim(text, prior.get("text", "")) >= 0.82\n            for prior in kept\n        ):\n            continue\n        kept.append(item)\n        if len(kept) >= limit:\n            break\n    kept.reverse()\n    return kept\n\n\n'''
if 'def _memory_relevant_to_listener(' not in s:
    if anchor not in s:
        raise SystemExit('memory worthy anchor missing')
    s = s.replace(anchor, insert, 1)

old_prune = '''def _prune_memory_state(mind):\n    for entity in ORDER:\n        state = mind.get("entities", {}).get(entity, {})\n        memories = []\n        for item in state.get("room_memories", []):\n            if not isinstance(item, dict):\n                continue\n            if _memory_worthy_text(item.get("text", ""), item.get("move")):\n                memories.append(item)\n        state["room_memories"] = memories[-220:]\n\n        self_history = []\n        for item in state.get("self_history", []):\n            if not isinstance(item, dict):\n                continue\n            if _memory_worthy_text(item.get("text", ""), item.get("move")):\n                self_history.append(item)\n        state["self_history"] = self_history[-220:]\n'''
new_prune = '''def _prune_memory_state(mind):\n    for entity in ORDER:\n        state = mind.get("entities", {}).get(entity, {})\n        memories = []\n        for item in state.get("room_memories", []):\n            if not isinstance(item, dict):\n                continue\n            # Pre-routing memories were broadcast into every mind and have no\n            # target metadata. Drop that inherited contamination once.\n            target_entity = str(item.get("target") or "").strip().lower()\n            listener_name = str(N.get(entity, entity)).strip().lower()\n            words = set(re.findall(r"[a-z][a-z'-]*", str(item.get("text") or "").lower()))\n            explicitly_relevant = target_entity == entity or entity in words or listener_name in words\n            if not explicitly_relevant:\n                continue\n            if _memory_worthy_text(item.get("text", ""), item.get("move")):\n                memories.append(item)\n        state["room_memories"] = _dedupe_memories(memories, 220)\n\n        self_history = []\n        for item in state.get("self_history", []):\n            if not isinstance(item, dict):\n                continue\n            if _memory_worthy_text(item.get("text", ""), item.get("move")):\n                self_history.append(item)\n        state["self_history"] = _dedupe_memories(self_history, 220)\n'''
if old_prune in s:
    s = s.replace(old_prune, new_prune, 1)
elif new_prune not in s:
    raise SystemExit('memory prune anchor missing')

old_record = '''    for listener in ORDER:\n        memories = mind["entities"][listener].setdefault("room_memories", [])\n        if worthy:\n            memories.append({\n                "source": message["id"],\n                "status": "observed",\n                "speaker": message["speaker"],\n                "text": message["text"][:300],\n                "move": message["cognition"].get("move_type"),\n                "discourse": message["discourse_id"],\n                "beat_id": message["beat_id"],\n                "topic_episode": message["cognition"].get("topic_episode"),\n            })\n            mind["entities"][listener]["room_memories"] = memories[-220:]\n        mind["entities"][listener]["last_event"] = message["id"]\n'''
new_record = '''    for listener in ORDER:\n        memories = mind["entities"][listener].setdefault("room_memories", [])\n        if worthy and _memory_relevant_to_listener(message, listener):\n            memories.append({\n                "source": message["id"],\n                "status": "observed",\n                "speaker": message["speaker"],\n                "target": message["cognition"].get("target"),\n                "text": message["text"][:300],\n                "move": message["cognition"].get("move_type"),\n                "discourse": message["discourse_id"],\n                "beat_id": message["beat_id"],\n                "topic_episode": message["cognition"].get("topic_episode"),\n            })\n            mind["entities"][listener]["room_memories"] = _dedupe_memories(memories, 220)\n        mind["entities"][listener]["last_event"] = message["id"]\n'''
if old_record in s:
    s = s.replace(old_record, new_record, 1)
elif new_record not in s:
    raise SystemExit('memory record anchor missing')

p.write_text(s)
